version: 2
jobs:
  build:
    docker:
      - image: gcc

    steps:
      - checkout

      - run:
          name: Build source code
          command: g++ bootstrap/main.cpp
          command: echo "Testing source code build . . ."