version: 2
jobs:
  build:
    docker:
      - image: gcc

    steps:
      - checkout

      - run:
          name: Build
          command: g++ bootstrap/main.cpp
      - run:
          name: Checking artifact
          command: ls bootstrap
      - run:
          name: Executing artifact
          command: ./bootstrap/a.out