version: 2
jobs:
  build:
    docker:
      - image: gcc

    steps:
      - checkout

      - run:
          name: Build
          command: make all
      - run:
          name: Checking artifact
          command: ls ./arcade
